from typing import Protocol

class NotebookRepository(Protocol):
    def save_notebook(self, record: dict) -> dict: ...
    def get_notebook(self, notebook_id: str, user_id: str | None = None) -> dict | None: ...
    def list_notebooks(self, user_id: str) -> list[dict]: ...
    def delete_notebook(self, notebook_id: str, user_id: str) -> None: ...
