from typing import Protocol

class LLMClient(Protocol):
    def generate_script(self, prompt: str) -> str: ...
    def generate_title(self, source_text: str) -> str: ...

class PodcastStorage(Protocol):
    def read_extracted_text(self, user_id: str, file_id: str) -> str: ...
    def save_script_file(self, user_id: str, script_id: str, payload: dict) -> str: ...

class ScriptRepository(Protocol):
    def save_script(self, record: dict) -> dict: ...
    def get_script(self, script_id: str, user_id: str | None = None) -> dict | None: ...
    def list_scripts(self, user_id: str) -> list[dict]: ...

class PodcastRepository(Protocol):
    def get_file(self, file_id: str, user_id: str | None = None) -> dict | None: ...
    def get_script(self, script_id: str, user_id: str | None = None) -> dict | None: ...
    def get_audio(self, audio_id: str, user_id: str | None = None) -> dict | None: ...
    def list_audio(self, user_id: str) -> list[dict]: ...
    def delete_audio(self, audio_id: str, user_id: str) -> None: ...

class AudioUrlResolver(Protocol):
    def resolve_audio_url(self, storage_uri: str, fallback_url: str) -> str: ...
